name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        env:
          PIP_CACHE_DIR: ~/.cache/pip
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir "$PIP_CACHE_DIR" -r requirements.txt
          pip install --cache-dir "$PIP_CACHE_DIR" flake8
      - name: Run flake8
        run: |
          flake8
      - name: Run coverage
        run: |
          coverage run -m pytest --disable-warnings -q
          coverage xml
          coverage html
          coverage report -m
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
